---
title: "iteration"
author: "Yaduo Wang"
date: "2023-11-12"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
```

## Lists
You can put anything in a list.
```{r}
l = list(vec_numeric = 5:8,
         vec_logical = c(TRUE, TRUE, FALSE, TRUE, FALSE,FALSE),
         mat = matrix(1:8, nrow = 2, ncol = 4),
         summary = summary(rnorm(100)))

mean(l[["vec_numeric"]])
```

## for loop
Creat a new list

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )
list_norms[["a"]]
```

Pause and get my old function
```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
mean_and_sd(list_norms[[1]])
mean_and_sd(list_norms[[2]])
mean_and_sd(list_norms[[3]])
mean_and_sd(list_norms[[4]])
```

Let's use a for loop:
```{r}
output = vector("list", length = 4)
for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```

## Let's try map
```{r}
output = map(list_norms, mean_and_sd)
```

Want a different function.
```{r}
output = map(list_norms, median)
```

## map variants
```{r}
output = map_dbl(list_norms, median, .id = "input")
```

```{r}
output = map_df(list_norms, mean_and_sd, .id = "input")
```

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )
listcol_df |> pull(name)
listcol_df |> pull(samp)
```

```{r}
listcol_df$samp[[1]]
```

```{r}
mean_and_sd(listcol_df$samp[[1]])
```

Can I just map?
```{r}
map(listcol_df$samp, mean_and_sd)
```

Can I add a list column?

```{r}
listcol_df |> 
  mutate(summary = map(samp, mean_and_sd),
         medians = map_dbl(samp, median))
```

## Weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
weather_nest = 
  nest(weather_df, data = date:tmin)

weather_nest

weather_nest |> pull(data)
```

Suppose I want to regress tmax or tmin for each station.
```{r}
weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}
map(weather_nest$data, weather_lm)
```

What about a map in a list column.
```{r}
weather_nest = 
  weather_nest |> 
  mutate(models = map(data, weather_lm))
```

```{r}
weather_nest$models
```

